### ISSUE TITLE
Translation to Portuguese Brazilian

### ISSUE THREAD

**Issue by Turhel** [edbmods/EdBPrepareCarefully#105]
### **Replace the archive original (english) to this archive**
[EdBPrepareCarefully.zip](https://github.com/edbmods/EdBPrepareCarefully/files/720285/EdBPrepareCarefully.zip)

Folder:
EdBPrepareCarefully\Languages\English\Keyed\

**Comment by edbmods** [comment]
Thanks for putting together a translation, but unfortunately I will not be able to integrate translations into the mod.  See the note that I added to the README on the main page: https://github.com/edbmods/EdBPrepareCarefully
