### ISSUE TITLE
Health conditions aren't removed when generating a random character

### ISSUE THREAD

**Issue by demize** [edbmods/EdBPrepareCarefully#123]
This applies to A17 Test 4. If you generate a random character in place of an existing one, it won't remove existing health conditions but it will generate new ones. Since I'm trying to generate mostly random characters and slightly adjust them to match the roles I want, this results in massive stacks of health conditions. The colonist probably wouldn't be able to stand the residual pain from all the old gunshots and scars.

**Comment by demize** [comment]
This is still an issue in the final release, however I did notice that it appears not to continue over to the actual scenario. I randomized three colonists until they had nice long lists of ailments, and only one colonist had any once I started the scenario (and only three of them, asthma in both lungs and a scar).

**Comment by edbmods** [comment]
Thanks so much for reporting this.  Unfortunately, I wasn't paying attention to bug reports here and didn't notice your post!  Sorry about that.  Fixed in the 0.17.1.2 version.
