### ISSUE TITLE
Exceptions when using left / right arrow on traits

### ISSUE THREAD

**Issue by MrWashingToad** [edbmods/EdBPrepareCarefully#163]
[output_log.txt](https://github.com/edbmods/EdBPrepareCarefully/files/1053072/output_log.txt)

Errors when a trait is selected that cannot exist with another trait. Found by having character have "pretty" trait selected originally as 3rd trait.  1st trait was "teetotaler" - I selected right arrow a few times to see what else was available, as soon as it hit the "ugly" trait, it threw exceptions. 

Repeatable.
Fix would be to somehow check for existing traits in all slots and prevent left/right arrow scrolling from selecting traits that cannot be combined.

Also - thanks for the amazing mod!!!
-MrWashingToad
RimWorld name in game: David "Wildfire" Sewell

**Comment by edbmods** [comment]
This should be fixed in v0.17.1.6.  The mod should now skip over disabled traits when you use the previous and next buttons.

**Comment by edbmods** [comment]
Thanks for the bug report!
