### ISSUE TITLE
Some "start near" scenario items don't spawn

### ISSUE THREAD

**Issue by edbmods** [edbmods/EdBPrepareCarefully#184]
Customize a scenario so that it includes ship chunks as "start near" items.  If you prepare carefully and then start the game, those ship chunks will not spawn.

The mod needs to recognize that some items are not the same as customizable equipment.  It should preserve any start near scenario parts that are for these special-case items.

**Comment by sdp0et** [comment]
I'm not sure if it's the same cause, but some items I select to spawn with do not spawn and are not manually displayed in the equipment.  Two examples I have noticed are both items (a weapon Rim of Madness Cults and a weapon-like item from Right Tool)

**Comment by sdp0et** [comment]
Also, Ship chunks spawn for me, but I had them set on "spawn randomly" rather than near

**Comment by edbmods** [comment]
Closing stale issue.

**Comment by edbmods** [comment]
Closing stale issue.
