### ISSUE TITLE
Error Loading a Pawn from a Save

### ISSUE THREAD

**Issue by Monterey13** [edbmods/EdBPrepareCarefully#196]
Error when loading a character from a save.  The error repeats. https://gist.github.com/0be013ff7eead432666d98fce6bb6ed9

**Comment by edbmods** [comment]
Unfortunately, this one will be difficult for me to duplicate without the saved preset or character file.

**Comment by edbmods** [comment]
Closing this one for now.  If you run into the problem after 1.0 comes out, please create a new issue.
