### ISSUE TITLE
I click prepare carefully and nothing happens

### ISSUE THREAD

**Issue by explosion56** [edbmods/EdBPrepareCarefully#203]
when I click the prepare carefully button it doesn't do anything

**Comment by chaos17** [comment]
I've the same problem since I installed mods to add new races:
https://i.imgur.com/vDSUR3A.png

**Comment by edbmods** [comment]
I tried with the mods listed in the above comment--at least all of the ones that are still compatible with RimWorld 1.0--and I cannot reproduce the problem.  Closing for now.  Reopen if you're still having the same issue and if you can narrow down the problem to a smaller set of mods.
