### ISSUE TITLE
Prepare carefully button does not open a window.

### ISSUE THREAD

**Issue by PettyBitch** [edbmods/EdBPrepareCarefully#210]
When attempting to click on prepare carefully, the game will freeze for a minute and nothing will happen.
A few things I think are worth mentioning:

On world generation, this error is spit out:
**Could not find player faction.
Verse.Log:Error(String)
RimWorld.Faction:get_OfPlayer()
RimWorld.Planet.TileFinder:RandomStartingTile()
ThatsAMoon.WorldGenStep_Moons:AddDestroyedMoon()
ThatsAMoon.WorldGenStep_Moons:GenerateFresh(String)
RimWorld.Planet.WorldGenerator:GenerateWorld(Single, String, OverallRainfall, OverallTemperature)
RimWorld.Page_CreateWorldParams:<CanDoNext>m__0()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.LongEventHandler:<UpdateCurrentAsynchronousEvent>m__1()**

Clicking on the buttom will freeze the game, and after a while this error is spit out:
**Exception filling window for RimWorld.Page_ConfigureStartingPawns: System.NullReferenceException: Object reference not set to an instance of an object
at EdB.PrepareCarefully.ProviderFactions..ctor () <0x000fe>
at EdB.PrepareCarefully.PrepareCarefully.InitializeProviders () <0x0019f>
at EdB.PrepareCarefully.PrepareCarefully.Initialize () <0x00023>
at EdB.PrepareCarefully.HarmonyPatches.DoWindowContentsPostfix (UnityEngine.Rect,RimWorld.Page_ConfigureStartingPawns) <0x00171>
at (wrapper dynamic-method) RimWorld.Page_ConfigureStartingPawns.DoWindowContents_Patch1 (object,UnityEngine.Rect) <0x0052b>
at Verse.Window/<WindowOnGUI>c__AnonStorey0.<>m__0 (int) <0x00735>**

**Verse.Log:Error(String)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)**

Full log: https://pastebin.com/SvEXnnQ1

I am on Rimworld V18.722, the minimum version that PrepareCarefully will run.

**Comment by edbmods** [comment]
Thanks for the pastebin of the logs.  That does give me an idea of where the error is happening.  Can you also paste the list of mods that you are using?  It's almost always a mod incompatibility that causes these problems, and I can't fix it unless I know the mod list and the mod load order.

**Comment by edbmods** [comment]
Closing stale issue.

**Comment by edbmods** [comment]
Going through and closing old issues that are probably no longer relevant.
