### ISSUE TITLE
EdbPrepareCarefully 1.0.4 bug: window's editor doesn't appear.

### ISSUE THREAD

**Issue by earphone555** [edbmods/EdBPrepareCarefully#230]
just like the title said. when clicked the button, the window doesn't appear.
gladly the 1.0.3 version just work fine here.

**Comment by edbmods** [comment]
If you are running other mods, please disable them and try again to make sure it's not a mod conflict.  Also confirm that you are running the required version of RimWorld.  It must be at least version 1.0.1969

**Comment by edbmods** [comment]
I'm going to close this issue since we're pretty far past this version now.  Re-open with more details if necessary.
