### ISSUE TITLE
Points calculation after switching Pawns between World and Colony

### ISSUE THREAD

**Issue by schoos76** [edbmods/EdBPrepareCarefully#243]
It seems that the calculation for the points spent is not working correctly when you switch Pawns between World and Colony.

How to reproduce: 
1. Move one pawn from World to Colony, points get deducted
2. Move another pawn from Colony to World, seems that points get deducted again.

Please also see this screenshot here:
![20181001064246_1](https://user-images.githubusercontent.com/4555004/46263765-ec240900-c545-11e8-8abd-01558fc36db3.jpg)

I've switched in Azzura and removed Kasen from the colony.

Let me know in case you need more information.

**Comment by edbmods** [comment]
Fixed in 1.0.12
