### ISSUE TITLE
One can get cowboy hat and duster made of steel or plasteel

### ISSUE THREAD

**Issue by b606** [edbmods/EdBPrepareCarefully#249]
Step to reproduce (using unlimited points):
1. Select a pawn, then the hat category
2. First, choose an item that can be made of hard material (helmet or armor) and select plasteel as material.
3. Do not change the material, but instead change the selection button above it to cowboy hat. 
4. Change the category to Top Clothing Layer and proceed similarly for duster.
5. Save the preset and continue to the game ;-)

Should this be classified as a bug ?

**Comment by edbmods** [comment]
Should be fixed with the newer apparel UI.
