### ISSUE TITLE
Steam Upload

### ISSUE THREAD

**Issue by TheKrush** [edbmods/EdBPrepareCarefully#25]
You should publish this on steam, it's really easy to do and then we'd have an official version up not the http://steamcommunity.com/sharedfiles/filedetails/?id=730384066 that's up there now.

**Comment by TheKrush** [comment]
Figure you should at least do one publish on steam as the original author then you could always add someone else to the workshop upload to take over and still retain the credit on it. I'll look over what your code is actually doing this weekend and see if it's something I might be up to helping with.

**Comment by edbmods** [comment]
Agree.  I'm going to ahead and finish up some bug fixes and publish a version to Steam this weekend.

**Comment by TheKrush** [comment]
Very cool, the mod is extremely useful so I can I assist after I look through the code in anyway I'd be more than happy to.

**Comment by edbmods** [comment]
Now available in the Steam Workshop.
