### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by b606** [edbmods/EdBPrepareCarefully#250]
Hi, 

I just made the french translation files for this mod  (https://github.com/b606/EdBPrepareCarefully-fr).
Could you please check whether it is ok ?

Whenever you want the files to be PR-ed here, just let me know (maintaning a mod for one file is ...).
Best regards

**Comment by edbmods** [comment]
I do appreciate that you took the time to create a translation, but unfortunately, I am not merging translations in the mod.  Please see my note here: https://github.com/edbmods/EdBPrepareCarefully#contributing-translations
