### ISSUE TITLE
Unable to generate pawns using templates from playable faction

### ISSUE THREAD

**Issue by AndrewTijua** [edbmods/EdBPrepareCarefully#267]
Looking at the code (with my lack of experience) this seems to be deliberate, but this creates issues with some race mods. 

If it is possible please consider allowing selection of pawns from playable factions.

**Comment by edbmods** [comment]
Closing this issue.  It applies to an old version and there isn't enough additional information to reproduce.  There were some changes to the way that alien race mods are supported--hopefully this resolves the problem.  Please re-open it if you see it happening in a 1.1 version of the mod and be sure to give some example mods and factions for which it's not working.
