### ISSUE TITLE
Please add translations

### ISSUE THREAD

**Issue by lex1975** [edbmods/EdBPrepareCarefully#272]
Please add translations

Russian translation for EdBPrepareCarefully 1.0.15
[Russian.zip](https://github.com/edbmods/EdBPrepareCarefully/files/3907893/Russian.zip)
I don’t know how to pull request, sorry.

**Comment by edbmods** [comment]
Please refer to this:
https://github.com/edbmods/EdBPrepareCarefully#contributing-translations

I'm sorry, but we won't be adding any translations directly to the mod.
