### ISSUE TITLE
Issue with humanoid alien races 2.0

### ISSUE THREAD

**Issue by Zenmusashi** [edbmods/EdBPrepareCarefully#274]
I don't know if this was brought up before, it's my first time posting here but I am getting an error that only appears to happen when I have edb and humanoid alien races 2.0 loaded, it states i can not find head type for humans.
![20191226192037_1](https://user-images.githubusercontent.com/7834788/71494519-c7384780-2815-11ea-8824-5cec45fee13b.jpg)

If I remove said mod the problem disappears. If I use character editor the problem also disappears so I am pretty sure there is a conflict between edb and humanoid.

**Comment by edbmods** [comment]
Going through and closing old issues that are probably no longer relevant.
