### ISSUE TITLE
Error while generating map

### ISSUE THREAD

**Issue by Bornholio** [edbmods/EdBPrepareCarefully#293]
Error:  Could not generate starting map because there is no player faction base.

https://gist.github.com/bb4c69fc9c9e580d1e08913c23bb7306

turning off recently installed mods had no effect.
uninstalled:
`XND tinyTools
Gloomy Hair mk2
Zitool object seeker
no water no life [1.1]
expanded roofing`
Function returned
Reinstalled each one at a time, function remains good.

**Comment by edbmods** [comment]
Going through and closing old issues that are probably no longer relevant.
