### ISSUE TITLE
Psychic Amplifiers cannot be added as a health condition.

### ISSUE THREAD

**Issue by angstbladecontrol** [edbmods/EdBPrepareCarefully#296]
Bug for Rimworld 1.1 Royalty

Psychic amplifier is not available as an Injury or Implant option. The amplifier does not have an install recipe. It's also the only implant in the base game (that I can find) which extends the Hediff_ImplantWithLevel class.

I don't really have rimworlding modding experience but I do think I have a hacky ass quarter of a solution (though you probably want something more robust and compatible with other mods that use leveled implants).

I'm not sure how the diffferent stages of the implant works. I tested it out by adding it as an injury option. I allowed hediff with defname PsychicAmplifier to pass through the implant filter when intializing injury options. This lets me select Psychic Amplifier as an Injury. I can choose from 6 different severities, although for some strange reason, severity 1 shows up as 5.

However, it always starts the colonist with a level 1 implant and a single random level 1 skill, ignoring whatever severity I select. Also, it is applied to the whole body instead of brain.

I tried what the game does in PawnGenerator:

`Hediff_ImplantWithLevel hediff_ImplantWithLevel = HediffMaker.MakeHediff(HediffDefOf.PsychicAmplifier, pawn, pawn.health.hediffSet.GetBrain()) as Hediff_ImplantWithLevel;`

`pawn.health.AddHediff(hediff_ImplantWithLevel);`

`hediff_ImplantWithLevel.SetLevelTo(num);`

inside Injury.AddToPawn method.

That almost kinda works at the most basic level. The pawns start with implant of the correct level applied to the brain a bunch of random abilities up to the severity I choose. The issue here i think is that the abilities are given during the menu before the game starts. This means I can generate a pawn with more abilities than they should know by selecting a high level amp and then changing the level/removing the amp. The abilities don't get removed. The pawn abilitytracker ability list needs to be cleared when psychic amp gets removed.

Also this doesn't work with presets which causes all the amps to just get set back to level 1.

**Comment by edbmods** [comment]
Fixed in v1.3.9
