### ISSUE TITLE
Don't work with 1.3 version

### ISSUE THREAD

**Issue by Osyruu** [edbmods/EdBPrepareCarefully#305]
Hey, on the version 1.3 the mods didn't work, could you fix it ASAP? I really want to custom my colony, thx :D

![image](https://user-images.githubusercontent.com/22823858/125409023-c8ab6f80-e3bb-11eb-983d-a75901678f2e.png)

**Comment by Bornholio** [comment]
https://github.com/Menoikeus/EdBPrepareCarefully/tree/BeardSupport Has temporary support with some bugs.

RimWorld>  Workshop > ditty's Workshop
EdB Prepare Carefully (Unofficial 1.3 Patch)

**Comment by Osyruu** [comment]
Thx :D

**Comment by edbmods** [comment]
Try the latest version.  It works with 1.3 now.
