### ISSUE TITLE
Seems to have an issue with GoG version of the game. (Edit: seems to be solved by updating game version)

### ISSUE THREAD

**Issue by RandDenner** [edbmods/EdBPrepareCarefully#310]
Will not work at all with the GoG version 1.3.3076, despite being properly installed and the **only active mod**.
Pressing the button causes the "Failed to initialize" window to open properly, but that is all.
Position in gamefiles/mod order makes no difference, nor do any game settings.
Attempted with 100% default choices, mod would still not initialize.

Edit: further testing indicates this mod version 1.3.1 seems to work fine with later GoG game version 1.3.3080 rev661.

![Prepare Carefully 1](https://user-images.githubusercontent.com/73523034/128877314-e5cba3c3-172c-49fa-bd49-bed7aec85394.png)
![Prepare Carefully 2](https://user-images.githubusercontent.com/73523034/128877317-89568dda-d191-414c-9256-d911392c3f98.png)

**Comment by Fixles** [comment]
Same issue :(

**Comment by cottonthread** [comment]
Same here

**Comment by RandDenner** [comment]
Just finished testing with updated GoG version of Rimworld+Royalty+Ideology v1.3.3080 rev 661.
Mod version 1.3.1 seems to be working fine with that so far as I can tell.

**Comment by edbmods** [comment]
Yes, the mod requires at least 1.3.3080.  I'll update the error message to make that more clear.
