### ISSUE TITLE
Error while generating pawn

### ISSUE THREAD

**Issue by TeaCrab** [edbmods/EdBPrepareCarefully#312]
Full Hugs Log:
https://gist.github.com/e9271a19bc6d982150a9de8eade4ec9f

This happens when pressing the Randomize button in Prepare Carefully window.
The error seems to only happen when a relationship is being generated.

Seems like a problem with Androids/Androids Expanded?  Randomizing appearance on some very bare-minimum Drones also causes an unrecoverable exception if Visual Exceptions is also used (Invisible UI layer blocking all mouse button inputs - scroll wheel works).

Maybe these simplistic pawns weren't supposed to be used as starting pawns with EDB PrepareCarefully?

**Comment by edbmods** [comment]
I think this is now fixed.  Try the latest version of the mod.
