### ISSUE TITLE
Prepare Carefully disabled

### ISSUE THREAD

**Issue by hutonahill** [edbmods/EdBPrepareCarefully#313]
getting this [error](https://imgur.com/Ykw8eLG). happens with no mods, not even royalty and ideology.

**Comment by edbmods** [comment]
Double-check which version of RimWorld that you are playing with (displayed in the upper-left corner when you start the game).  You need at least version 1.3.3080 of the game for the mod to work.  That's the most common reason that you'll see that error.  I'll update the error message to make that clear.
