### ISSUE TITLE
Humanoid Alien Races framework: Cannot change apparel when race is set to only use race-restricted apparel

### ISSUE THREAD

**Issue by sumghai** [edbmods/EdBPrepareCarefully#317]
**Issue Description:**
When using EdB PrepareCarefully with the Humanoid Alien Races (HAR) framework, if the alien pawn's has `onlyUseRaceRestrictedApparel` set to `true`, the player cannot change the pawn's apparel at all.

**Expected Behaviour:**
Pawns from alien races with apparel restrictions should still be allowed to change their apparel, and only pick from what is allowed for that race.

**Steps to Reproduce:**
1. Load the mods and versions described below in **System and Game Configuration**
2. Start a new colony
3. Select the `Mousekin Settlers` scenario
4. Select any storyteller AI, difficulty and game save mode
5. Generate a world with 5% coverage and no other factions (to expedite testing)
6. Select a random colony site
7. Enter the Prepare Carefully window from the character creation screen
8. Select any Mousekin pawn on the left side of the window
9. Go to the pawn's `Accessory`, `Hat`, `Top Clothing Layer`, `Middle Clothing Layer`, `Bottom Clothing Layer` or `Pants` layers, and observe that the apparel picker control remains stuck on `None` without any options available / selectable

**Additional information:**
The HAR framework includes various XML tags for controlling what apparel an alien race is allowed or prohibited from wearing:
* `apparelList` - Apparel that is only allowed to be worn by this race
* `whiteApparelList` - Apparel from other races that the current race is *also* allowed to wear
* `blackApparelList` - Apparel that this race is never allowed to wear
* `onlyUseRaceRestrictedApparel` - Boolean
 * if `true`, the alien pawn is only allowed to wear apparel from `apparelList` and `whiteApparelList`, and not `blackApparelList`
 * if `false`, the alien pawn can wear anything, effectively ignoring `whiteApparelList` and `blackApparelList`
 
Ideally, Prepare Carefully should check to see if a pawn's race's `onlyUseRaceRestrictedApparel` is true, and modify each of the apparel layer pickers to only show options from `apparelList` and `whiteApparelList`.

## System and Game Configuration
**Operating System:** Microsoft Windows 10 (64-bit), Version 21H1 (OS Build 19043.1237)
**Physical RAM:** 16.0 GB
**RimWorld base game version:** 1.3.3117
**RimWorld DLCs loaded:** none
**Mod list:**
* Harmony, 26 July 2021 update via Steam Workshop
* Core v1.3.3117
* Humanoid Alien Races, 10 August 2021 update via Steam Workshop
* EdB Prepare Carefully v1.3.9
* Mousekin Race v0.3 ([download link for development build](https://github.com/sumghai/MousekinRace/archive/refs/heads/main.zip))

**Comment by edbmods** [comment]
Fixed with release 1.3.11

**Comment by sumghai** [comment]
Fix confirmed - many, many thanks!
