### ISSUE TITLE
PrepareCarefully will not initialize while Biotech DLC is loaded regardless of load order.

### ISSUE THREAD

**Issue by ethanhulse** [edbmods/EdBPrepareCarefully#328]
After "dividing and conquering" for several hours I have determined that the sole commonality is Biotech. With every case of my game not initializing prepare carefully and receiving an error prompt at the character creation screen.
![image](https://user-images.githubusercontent.com/18195980/211180545-8a3823fe-1ef1-452b-a47b-8f13781e9e3e.png)
![image](https://user-images.githubusercontent.com/18195980/211180556-26dfcc9a-2c48-447a-bef6-735eb7135488.png)

**Comment by edbmods** [comment]
Going through and closing old issues that are likely no longer relevant.
