### ISSUE TITLE
Doesn't work with Biotech

### ISSUE THREAD

**Issue by PaninGitHub** [edbmods/EdBPrepareCarefully#331]
I don't know what it is, but this version of Prepare Carefully doesn't work with Biotech. The old fork version for 1.4 worked fine, but not this exact mod

I am using RimPy Mod Manager for running Rimworld. I thought it was the mods at first but I literally removed every mod except for the DLCs and Prepare Carefully and it still does not work

When Biotech is removed it will work fine. It seems to have a problem with Xenotyes:

[Prepare Carefully debug.txt](https://github.com/edbmods/EdBPrepareCarefully/files/11522543/Prepare.Carefully.debug.txt)

Yes I have divided and conquer for a couple hours. It's definitely Biotech. Plz fix

**Comment by edbmods** [comment]
Going through and closing old issues that are probably no longer relevant with the release of 1.5
