### ISSUE TITLE
Fleshmass Pawn Parts Not Working

### ISSUE THREAD

**Issue by rarcher** [edbmods/EdBPrepareCarefully#350]
At one point, it seemed like this was an intermittent issue, but this may have been due to updates to the mod itself.  In the current version, it seems to happen all the time, regardless of what you do.  It is observed to effect the following implants / health conditions:
- Flesh whip
- Flesh tentacle
- Fleshmass lung
- Fleshmass stomach

Observed problems are:

- Saving a pawn does not save any of the impacted implants / health conditions to the pawn file.  This has been confirmed by manual examination of the XML.
- Loading a pawn file with any of the impacted implants / health conditions (ie: from an earlier version of Prepare Carefully) fails to load the conditions in question.
- Closing Prepare Carefully removes all impacted implants / health conditions from pawns on the vanilla `Create characters` screen.

Note that this means you _can_ have a pawn with one of the effected implants / health conditions within Prepare Carefully; you just have to roll them with the vanilla pawn generator, and then open Prepare Carefully with them still up.

**Comment by rarcher** [comment]
This pawn file is known to have both Flesh tentacle and Flesh whip in it, but does not load either in the current version of Prepare Carefully.  The file extension has been changed to `.txt` so that GitHub will allow the upload - just rename it back to `.pcc` to use the file.

[Clover.txt](https://github.com/edbmods/EdBPrepareCarefully/files/15268394/Clover.txt)

**Comment by edbmods** [comment]
Thanks for letting me know.  I think I changed something when I added mechanitor implants that broke the way these load from the preset.  I will fix it and I will also add options to add these mutations in the implants & bionics dialog.

**Comment by rarcher** [comment]
No problem. Thank you!

**Comment by rarcher** [comment]
Additional data point:  A manually-installed version 1.5.6 of the mod does not exhibit the issue.

**Comment by edbmods** [comment]
Give it a try with the 1.5.11 that was just released.  It should be fixed now--and you should now see options for those implants in the dialog.

**Comment by rarcher** [comment]
Works great!  Thanks!
