### ISSUE TITLE
Illnesses are not picked up properly

### ISSUE THREAD

**Issue by edbmods** [edbmods/EdBPrepareCarefully#4]
Before scenarios were introduced, all colonists got cryptosickness, so it didn't need to be added to the list of "Injuries..." in the health section.

Cryptosickness is now randomly assigned to colonists in some scenarios, and other illnesses/conditions are assigned in other scenarios (i.e. malnutrition).  The code that builds the list of available injuries filters out illnesses, so they do not appear in the Health section in Prepare Carefully.  Code in the `InjuryManager` class and perhaps elsewhere will need to be updated to support them.

Also, "Injuries" maybe isn't the best label anymore if the list now includes illnesses.  Not sure if there's a good catch-all alternative.

**Comment by Fregrant** [comment]
Conditions? Health conditions? Health issues?

**Comment by drumanagh** [comment]
"Health condition" to match the scenario editor would probably be good.

**Comment by edbmods** [comment]
Yep.  I'm going to go with "conditions."

**Comment by edbmods** [comment]
Fixed in v0.14.0.5.
