### ISSUE TITLE
Missing deploy.bat

### ISSUE THREAD

**Issue by ShelbyZ** [edbmods/EdBPrepareCarefully#61]
EdBPrepareCarefully.csproj contains a reference to a custom command for the Debug build step as follow:

```
<CustomCommands>
    <CustomCommands>
      <Command type="AfterBuild" command="deploy.bat ${TargetFile}" workingdir="${ProjectDir}" />
    </CustomCommands>
</CustomCommands>
```

This prevents Xamarin Studio from building the Debug version.

**Comment by edbmods** [comment]
I committed a fix to remove this reference.  It was only in the Debug target.  I typically only use the Release target since debugging a Unity game from Visual Studio or MonoDevelop is not straightforward at all.

**Comment by ShelbyZ** [comment]
It's actually not too bad from Visual Studio, you need to attach to a running process (RimWorldWin.exe in this case) and assuming the mod is loaded it _should_ work.
