### ISSUE TITLE
v0.15.1.1 crash when built from source

### ISSUE THREAD

**Issue by ShelbyZ** [edbmods/EdBPrepareCarefully#62]
Building EdBPrepareCarefully from tag v0.15.1.1 and copying the assemblies into the appropriate folder having RimWorld with Core followed by EdB Prepare Carefully causes a crash on startup.  When removing the assemblies and restarting RimWorld the Debug log reports the following:

![mod errors](https://cloud.githubusercontent.com/assets/1033099/18111615/fc046dba-6ed5-11e6-823a-17431cec88f7.PNG)

**Comment by edbmods** [comment]
Thanks for pointing out these issues.  I've been using Xamarin Studio/MonoDevelop as my IDE, and missed these issues.  I see the same problem when building in Visual Studio.  Let me take a look.

**Comment by edbmods** [comment]
Double-check that the assemblies are in the correct place in the mod folder that you copy over into the RimWorld directory.  These errors look like the errors that you'd see if the DLL isn't there.  Your mod directory structure should look like this:

```
\EdBPrepareCarefully
   \About
   \Assemblies
       EdBPrepareCarefully.dll
   \Defs
   \Languages
   \Textures
```

**Comment by edbmods** [comment]
I should add a script that creates this mod directory.  I'll look into that.

**Comment by ShelbyZ** [comment]
It appears this is just an issue with how mods are loaded.  I had copied over both the assembly and pdb file and that caused the issue with it not being loaded correctly.

**Comment by biship** [comment]
For all the RimWorld github mod code I download and self compile, I adapt this file for them all:
https://github.com/RimWorldCCLTeam/CommunityCoreLibrary/blob/master/DLL_Project/PostBuild.txt
(It would be better if every mod did this, but I can live with changing the file per mod, and adding it to the post build.)
