### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by dragomano** [edbmods/EdBPrepareCarefully#72]
https://github.com/dragomano/EdBPrepareCarefully-ru

**Comment by Gungniir** [comment]
Wow, thx for translation

**Comment by edbmods** [comment]
Thanks for offering to adding a translation, but unfortunately I will not be able to integrate translations into the mod.  See the note that I added to the README on the main page: https://github.com/edbmods/EdBPrepareCarefully
